// Code generated by protoc-gen-gogo.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Request
	User
	Response
*/
package api

import regexp "regexp"
import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Request) Validate() error {
	if nil == this.User {
		return github_com_mwitkow_go_proto_validators.FieldError("User", fmt.Errorf("message must exist"))
	}
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}

var _regex_User_Id = regexp.MustCompile("^[a-zA-Z0-9]{3,10}$")

func (this *User) Validate() error {
	if !_regex_User_Id.MatchString(this.Id) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9]{3,10}$"`, this.Id))
	}
	if !(this.Age > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '-1'`, this.Age))
	}
	if !(this.Age < 151) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '151'`, this.Age))
	}
	if !(this.Height >= 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Height", fmt.Errorf(`value '%v' must be greater than or equal to '0'`, this.Height))
	}
	if !(this.Height <= 250) {
		return github_com_mwitkow_go_proto_validators.FieldError("Height", fmt.Errorf(`value '%v' must be lower than or equal to '250'`, this.Height))
	}
	return nil
}
func (this *Response) Validate() error {
	return nil
}
